hyperskill_project:
  id: 166
  ide_files: https://stepik.org/media/attachments/lesson/496562/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Mon, 04 Oct 2021 20:07:27 UTC
stages:
- id: 860
  step: 12369
  is_completed: true
- id: 861
  step: 12370
  is_completed: true
- id: 862
  step: 12371
  is_completed: true
- id: 863
  step: 12372
  is_completed: false
topics:
  0:
  - title: Overview of NLTK
    theory_id: 10022
  - title: Tokenization
    theory_id: 10363
  - title: Introduction to operating systems
    theory_id: 9704
  - title: Files
    theory_id: 13025
  - title: File types
    theory_id: 13017
  - title: XML
    theory_id: 6901
  - title: Regexps basics
    theory_id: 7580
  - title: Computer programming
    theory_id: 8739
  - title: Intro to computational thinking
    theory_id: 8742
  - title: Components of computational thinking
    theory_id: 8745
  - title: Introduction to OOP
    theory_id: 3614
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Naming variables
    theory_id: 5885
  - title: Taking input
    theory_id: 5913
  - title: Program with numbers
    theory_id: 5872
  - title: If statement
    theory_id: 5953
  - title: Else statement
    theory_id: 5932
  - title: Elif statement
    theory_id: 5926
  - title: For loop
    theory_id: 6065
  - title: Load module
    theory_id: 6019
  - title: Create module
    theory_id: 6057
  - title: Packages
    theory_id: 6384
  - title: Class
    theory_id: 6661
  - title: Class instances
    theory_id: 6669
  - title: Methods
    theory_id: 6931
  - title: Natural language processing
    theory_id: 9157
  - title: Regexps in Python
    theory_id: 9468
  - title: Escaping in regexps
    theory_id: 9754
  - title: Regexp sets and ranges
    theory_id: 10035
  - title: Shorthands
    theory_id: 10142
  - title: Regexp quantifiers
    theory_id: 10355
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and options
    theory_id: 9746
  - title: Pip
    theory_id: 6230
  - title: XML in Python
    theory_id: 9481
  - title: Introduction to Linux
    theory_id: 9526
  - title: File modes and permissions
    theory_id: 13953
  - title: Working with file modes and permissions
    theory_id: 13961
  - title: Files in Python
    theory_id: 8691
  - title: Reading files
    theory_id: 8139
  - title: Basic data types
    theory_id: 5852
  - title: Integer arithmetic
    theory_id: 5865
  - title: Quotes and multi-line strings
    theory_id: 5814
  - title: Escape sequences
    theory_id: 7130
  - title: Variables
    theory_id: 5859
  - title: Type casting
    theory_id: 6224
  - title: String formatting
    theory_id: 6037
  - title: List
    theory_id: 5979
  - title: Indexes
    theory_id: 6189
  - title: Invoking a function
    theory_id: 5891
  - title: Declaring a function
    theory_id: 5900
  - title: Scopes
    theory_id: 6322
  - title: Basic string methods
    theory_id: 6842
  - title: Boolean logic
    theory_id: 6025
  - title: Comparisons
    theory_id: 5920
  - title: Identity testing
    theory_id: 8077
  - title: Dictionary
    theory_id: 6481
  - title: List comprehension
    theory_id: 6315
  - title: Nested lists
    theory_id: 6938
  - title: Split and join
    theory_id: 6972
  - title: Defaultdict and Counter
    theory_id: 7989
  1:
  - title: Text normalization
    theory_id: 10451
  - title: Writing files
    theory_id: 8334
  2:
  - title: POS tagging
    theory_id: 10435
  - title: Tuple
    theory_id: 7462
  3:
  - title: Intro to text representations
    theory_id: 10443
  - title: Computer algorithms
    theory_id: 4953
  - title: Intro to Machine Learning
    theory_id: 10403
  - title: Introduction to sklearn
    theory_id: 10430
  - title: TF-IDF vectorizer
    theory_id: 12910
  - title: Math functions
    theory_id: 6256
